Update TPM clone command to specific commit
ms-iot/imx-iotcore pull request #41
Opened 2019-03-05 23:01 UTC by dmcilvaney

The reference implementation is being updated regularly, indicate that the TPM is an optional component. Also indicate a known good commit to checkout.

2019-03-05 23:38 UTC, hbeberman requested changes

2019-03-05 23:38 UTC, hbeberman commented on Documentation/build-arm64-firmware.md
> +    Optionally, clone the TPM reference implementation (`mu_platform_nxp` includes a copy of the TPM already)
```suggestion
    Optionally, clone the TPM reference implementation (`mu_platform_nxp` includes a precompiled TPM binary)
```

2019-03-05 23:38 UTC, hbeberman commented on Documentation/build-firmware.md
> +    Optionally, clone the TPM reference implementation (`imx-edk2-platforms` includes a copy of the TPM already)
```suggestion
    Optionally, clone the TPM reference implementation (`imx-edk2-platforms` includes a precompiled TPM binary)
```

2019-03-05 23:38 UTC, hbeberman commented on Documentation/build-arm64-firmware.md
> +    $ pushd .; cd .\ms-tpm-20-ref; git checkout 65b65354c6cce3212d9c512ec3ae2e23fe37c94d; popd
```suggestion
    $ pushd ms-tpm-20-ref; git checkout 65b65354c6cce3212d9c512ec3ae2e23fe37c94d; popd
```

2019-03-05 23:38 UTC, hbeberman commented on Documentation/build-firmware.md
> +    $ pushd .; cd .\ms-tpm-20-ref; git checkout 65b65354c6cce3212d9c512ec3ae2e23fe37c94d; popd
```suggestion
    $ pushd ms-tpm-20-ref; git checkout 65b65354c6cce3212d9c512ec3ae2e23fe37c94d; popd
```

2019-03-06 01:10 UTC, neilsh-msft commented
Can you update the arm64 documentation as well?

2019-03-06 19:15 UTC, dmcilvaney commented
We already updated build-arm64-firmware.md, unless there is somewhere else I'm missing.

2019-03-06 19:56 UTC, neilsh-msft approved these changes

2019-03-06 20:40 UTC, merged