Add GPIO support for MX6 ULL.
ms-iot/imx-iotcore pull request #8
Opened 2019-01-09 02:39 UTC by henie

2019-01-09 19:21 UTC, jordanrh1 requested changes
Be sure to test with [gpiotesttool](https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/BusTools/GpioTestTool) and preferably the [GPIO HLK tests](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/f1fc0922-1186-48bd-bfcd-c7385a2f6f96).

2019-01-09 19:24 UTC, hbeberman approved these changes

2019-01-09 19:24 UTC, hbeberman commented on driver/gpio/imxgpio/imx6ull.hpp
> +  // iMX6 Dual/Quad
```suggestion
  // iMX6 Dual/Quad ULL
```

2019-01-09 22:38 UTC, neilsh-msft requested changes

2019-01-09 22:38 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +    { IMX_MAKE_PIN_1(1, 21), 4, 0x590, 0 }, // IOMUXC_S- ALT4 - GPT1_CAPTURE2 - IOMUXC_GPT1_CAPTURE2_SELECT_INPUT
The first item in the description comment is missing the MUX_CTL_PAD value, did the script for parsing the NXP documentation fail here, or was this truncated by accident?

2019-01-09 22:38 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +    { IMX_MAKE_PIN_1(1, 4), 8, 0x644, 2 }, // IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO04 - ALT8 - UART5_TX - IOMUXC_UART5_RX_DATA_SELECT_INPUT
We don't support reversing the send/receive pins (DCE/DTE mode) in the UART driver, so any entries that map UARTx_TX to UARTx_RX and UARTx_RX to UARTx_TX should be commented out.

2019-01-09 22:38 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +    { IMX_MAKE_PIN_1(1, 6), 8, 0x620, 0 }, // IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO06 - ALT8 - UART1_CTS_B - IOMUXC_UART1_RTS_B_SELECT_INPUT
UARTx_CTS to UARTx_RTS and UARTx_RTS to UARTx_CTS should also be commented out.

2019-01-09 22:42 UTC, neilsh-msft commented
If you have access, can you post the perl script and source files you used to generate the imx6ull pin maps to https://microsoft.visualstudio.com/DefaultCollection/IOT/_git/iot.cli.selfenablement  under scripts\imx6ull_gpio\?  If you don't have access, please send me the files and I'll commit them.

2019-01-09 23:22 UTC, jordanrh1 commented
@neilsh-msft Maybe check in the perl scripts to this repository.

2019-01-11 18:47 UTC, neilsh-msft requested changes

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 3), 8, 0x624, 1 }, // IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO03 - ALT8 - UART1_RX - IOMUXC_UART1_RX_DATA_SELECT_INPUT
This is fine, uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 5), 8, 0x644, 3 }, // IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO05 - ALT8 - UART5_RX - IOMUXC_UART5_RX_DATA_SELECT_INPUT
This is fine, uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 7), 8, 0x620, 1 }, // IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO07 - ALT8 - UART1_RTS_B - IOMUXC_UART1_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 8), 8, 0x640, 1 }, // IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO08 - ALT8 - UART5_RTS_B - IOMUXC_UART5_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 17), 0, 0x624, 3 }, // IOMUXC_SW_MUX_CTL_PAD_UART1_RX_DATA - ALT0 - UART1_RX - IOMUXC_UART1_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 17), 9, 0x644, 5 }, // IOMUXC_SW_MUX_CTL_PAD_UART1_RX_DATA - ALT9 - UART5_RX - IOMUXC_UART5_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 19), 0, 0x620, 3 }, // IOMUXC_SW_MUX_CTL_PAD_UART1_RTS_B - ALT0 - UART1_RTS_B - IOMUXC_UART1_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 19), 9, 0x640, 4 }, // IOMUXC_SW_MUX_CTL_PAD_UART1_RTS_B - ALT9 - UART5_RTS_B - IOMUXC_UART5_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 21), 0, 0x62C, 1 }, // IOMUXC_SW_MUX_CTL_PAD_UART2_RX_DATA - ALT0 - UART2_RX - IOMUXC_UART2_RX_DATA_SELECT_INPUT
Umcomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 23), 0, 0x628, 1 }, // IOMUXC_SW_MUX_CTL_PAD_UART2_RTS_B - ALT0 - UART2_RTS_B - IOMUXC_UART2_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 25), 0, 0x634, 1 }, // IOMUXC_SW_MUX_CTL_PAD_UART3_RX_DATA - ALT0 - UART3_RX - IOMUXC_UART3_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 27), 0, 0x630, 1 }, // IOMUXC_SW_MUX_CTL_PAD_UART3_RTS_B - ALT0 - UART3_RTS_B - IOMUXC_UART3_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 29), 0, 0x63C, 1 }, // IOMUXC_SW_MUX_CTL_PAD_UART4_RX_DATA - ALT0 - UART4_RX - IOMUXC_UART4_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 31), 0, 0x644, 7 }, // IOMUXC_SW_MUX_CTL_PAD_UART5_RX_DATA - ALT0 - UART5_RX - IOMUXC_UART5_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 0), 1, 0x638, 0 }, // IOMUXC_SW_MUX_CTL_PAD_ENET1_RX_DATA0 - ALT1 - UART4_RTS_B - IOMUXC_UART4_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(1, 25), 4, 0x628, 3 }, // IOMUXC_SW_MUX_CTL_PAD_UART3_RX_DATA - ALT4 - UART2_RTS_B - IOMUXC_UART2_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 2), 1, 0x640, 5 }, // IOMUXC_SW_MUX_CTL_PAD_ENET1_RX_EN - ALT1 - UART5_RTS_B - IOMUXC_UART5_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 5), 1, 0x648, 3 }, // IOMUXC_SW_MUX_CTL_PAD_ENET1_TX_EN - ALT1 - UART6_RTS_B - IOMUXC_UART6_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 7), 1, 0x650, 1 }, // IOMUXC_SW_MUX_CTL_PAD_ENET1_RX_ER - ALT1 - UART7_RTS_B - IOMUXC_UART7_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 9), 1, 0x64C, 2 }, // IOMUXC_SW_MUX_CTL_PAD_ENET2_RX_DATA1 - ALT1 - UART6_RX - IOMUXC_UART6_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 11), 1, 0x654, 1 }, // IOMUXC_SW_MUX_CTL_PAD_ENET2_TX_DATA0 - ALT1 - UART7_RX - IOMUXC_UART7_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 13), 1, 0x65C, 1 }, // IOMUXC_SW_MUX_CTL_PAD_ENET2_TX_EN - ALT1 - UART8_RX - IOMUXC_UART8_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(2, 15), 1, 0x658, 1 }, // IOMUXC_SW_MUX_CTL_PAD_ENET2_RX_ER - ALT1 - UART8_RTS_B - IOMUXC_UART8_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(3, 1), 2, 0x63C, 3 }, // IOMUXC_SW_MUX_CTL_PAD_LCD_ENABLE - ALT2 - UART4_RX - IOMUXC_UART4_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(3, 3), 2, 0x638, 3 }, // IOMUXC_SW_MUX_CTL_PAD_LCD_VSYNC - ALT2 - UART4_RTS_B - IOMUXC_UART4_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(3, 10), 1, 0x658, 3 }, // IOMUXC_SW_MUX_CTL_PAD_LCD_DATA05 - ALT1 - UART8_RTS_B - IOMUXC_UART8_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(3, 12), 1, 0x650, 3 }, // IOMUXC_SW_MUX_CTL_PAD_LCD_DATA07 - ALT1 - UART7_RTS_B - IOMUXC_UART7_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(3, 22), 1, 0x654, 3 }, // IOMUXC_SW_MUX_CTL_PAD_LCD_DATA17 - ALT1 - UART7_RX - IOMUXC_UART7_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(3, 26), 1, 0x65C, 3 }, // IOMUXC_SW_MUX_CTL_PAD_LCD_DATA21 - ALT1 - UART8_RX - IOMUXC_UART8_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 7), 8, 0x62C, 3 }, // IOMUXC_SW_MUX_CTL_PAD_NAND_DATA05 - ALT8 - UART2_RX - IOMUXC_UART2_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 9), 8, 0x628, 5 }, // IOMUXC_SW_MUX_CTL_PAD_NAND_DATA07 - ALT8 - UART2_RTS_B - IOMUXC_UART2_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 13), 8, 0x634, 3 }, // IOMUXC_SW_MUX_CTL_PAD_NAND_CE0_B - ALT8 - UART3_RX - IOMUXC_UART3_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 15), 8, 0x630, 3 }, // IOMUXC_SW_MUX_CTL_PAD_NAND_CLE - ALT8 - UART3_RTS_B - IOMUXC_UART3_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 18), 8, 0x64C, 3 }, // IOMUXC_SW_MUX_CTL_PAD_CSI_PIXCLK - ALT8 - UART6_RX - IOMUXC_UART6_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 19), 8, 0x648, 0 }, // IOMUXC_SW_MUX_CTL_PAD_CSI_VSYNC - ALT8 - UART6_RTS_B - IOMUXC_UART6_RTS_B_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 22), 8, 0x644, 1 }, // IOMUXC_SW_MUX_CTL_PAD_CSI_DATA01 - ALT8 - UART5_RX - IOMUXC_UART5_RX_DATA_SELECT_INPUT
Uncomment.

2019-01-11 18:47 UTC, neilsh-msft commented on driver/gpio/imxgpio/imx6ull.hpp
> +//  { IMX_MAKE_PIN_1(4, 23), 8, 0x640, 7 }, // IOMUXC_SW_MUX_CTL_PAD_CSI_DATA02 - ALT8 - UART5_RTS_B - IOMUXC_UART5_RTS_B_SELECT_INPUT
Uncomment.

2019-01-16 03:06 UTC, henie commented
IO mux header file changed. Tested with gpiotest tool.

2019-01-16 17:22 UTC, jordanrh1 approved these changes

2019-01-16 18:21 UTC, neilsh-msft approved these changes

2019-01-16 18:25 UTC, christopherco approved these changes

2019-01-16 18:59 UTC, merged